INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Mass Effect Trilogy', 4.8, 2012, 'Role-playing (RPG), Shooter', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/1.png', 'Uma trilogia épica de RPG de ficção científica onde suas escolhas moldam a história e o destino da galáxia.', 'A saga de Shepard, um comandante espacial que lidera uma luta contra a aniquilação galáctica causada pelos Reapers. Embarque em uma narrativa profunda, interativa e repleta de personagens marcantes, conflitos éticos e decisões que têm consequências reais em um universo vasto e detalhado.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Red Dead Redemption 2', 4.7, 2018, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/2.png', 'Um épico de faroeste sobre lealdade, sobrevivência e o fim de uma era.', 'Ambientado em um vasto mundo aberto no final do século XIX, este jogo conta a história de Arthur Morgan, membro de uma gangue de foras-da-lei. Vivencie dramas pessoais, encontros emocionantes e uma recriação deslumbrante da América em transformação, com sistemas complexos de jogabilidade e imersão sem precedentes.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Um RPG de fantasia com uma história rica, decisões impactantes e um vasto mundo aberto.', 'Jogue como Geralt de Rívia, um caçador de monstros, em busca de sua filha adotiva enquanto enfrenta ameaças sobrenaturais. Explore terras vibrantes, resolva conflitos morais, enfrente criaturas aterrorizantes e aproveite uma narrativa que equilibra drama, intriga e ação.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'Um intenso jogo de ação ambientado no Japão feudal, onde honra e vingança guiam sua jornada.', 'Assuma o papel de um shinobi traído que busca resgatar seu mestre e recuperar sua honra. Com combates desafiadores e mecânicas de furtividade, o jogo combina narrativa emocional com um sistema de combate preciso e exigente, ambientado em um mundo visualmente impressionante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ghost of Tsushima', 4.6, 2012, 'Role-playing (RPG), Adventure', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Um samurai luta pela liberdade de sua terra contra invasores mongóis no Japão feudal.', 'Siga Jin Sakai em sua transformação de samurai honrado para guerreiro fantasma enquanto ele defende a ilha de Tsushima. Com um mundo aberto de tirar o fôlego, combates emocionantes e escolhas morais, o jogo celebra a cultura japonesa e o espírito da resistência.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Super Mario World', 4.7, 1990, 'Platform', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Uma aventura clássica em plataformas onde Mario e Luigi salvam o Reino dos Cogumelos.', 'Explore o icônico mundo dinâmico de Dinosaur Land, enfrentando desafios, inimigos criativos e segredos escondidos. Este jogo definiu o gênero de plataforma com seu design inovador, trilha sonora cativante e jogabilidade atemporal.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Hollow Knight', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Um metroidvania sombrio e atmosférico em um mundo subterrâneo habitado por insetos.', 'Explore o reino de Hallownest como um cavaleiro solitário, enfrentando perigos e revelando segredos. Com arte desenhada à mão, combates desafiadores e uma narrativa minimalista, o jogo oferece uma experiência profundamente imersiva e gratificante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Ori and the Blind Forest', 4, 2015, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Um jogo de aventura visualmente deslumbrante com uma história emocionante e mecânicas fluidas.', 'Siga Ori, um espírito guardião, em sua jornada para salvar uma floresta moribunda. Este jogo combina plataformas desafiadoras, design artístico de tirar o fôlego e uma trilha sonora comovente, criando uma experiência inesquecível e emocionalmente impactante.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Cuphead', 4.6, 2017, 'Platform', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Um jogo de ação inspirado nos desenhos animados dos anos 1930, com combates intensos e visuais únicos.', 'Controle Cuphead e Mugman em uma série de batalhas contra chefes desafiadores enquanto tentam pagar uma dívida ao Diabo. Com gráficos desenhados à mão, trilha sonora de jazz vibrante e jogabilidade difícil, o jogo é uma homenagem ao passado com um toque moderno.');
INSERT INTO tb_game (title, score, game_year, genre, platforms, img_url, short_description, long_description) VALUES ('Sonic CD', 4, 1993, 'Platform', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'Uma aventura de alta velocidade onde Sonic enfrenta o Dr. Robotnik e salva Amy Rose.', 'Viaje no tempo para salvar o Little Planet neste clássico de Sonic, combinando jogabilidade rápida e exploração. Com níveis inovadores, trilha sonora marcante e o surgimento de Metal Sonic, este jogo é um marco na franquia do ouriço azul.');
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, position) VALUES (2, 10, 4);